### ISSUE TITLE
Exception on update after upgrade from 3.4.1 to 3.5.1 

### ISSUE THREAD

**Issue by RailsGuy** [osm-search/Nominatim#1946]
Hi there, I've upgraded from 3.4.1 to 3.5.1 and run the database migration. All good until I re-started updates and get this error. This is on ubuntu 18.04 and "python3-psycopg2 is already the newest version (2.7.4-1)."
Any ideas?

Thank you

```
update.php --import-osmosis-all
Currently at sequence 4159260 (20/08/2020 14:13:02) -  indexed
'/srv/nominatim-3-5-1/Nominatim-3.5.1/nominatim/nominatim.py' --database nominatim --port 5432 --threads 1
WARNING: Starting indexing rank (0 to 30) using 1 threads
WARNING: Starting rank 0
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 0

WARNING: Starting rank 1
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 1

WARNING: Starting rank 2
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 2

....

WARNING: Starting rank 21
WARNING: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 21

WARNING: Starting rank 22
Traceback (most recent call last):
  File "/srv/nominatim-3-5-1/Nominatim-3.5.1/nominatim/nominatim.py", line 178, in is_done
    if self.conn.poll() == psycopg2.extensions.POLL_OK:
psycopg2.ProgrammingError: function getnearestroadplaceid(smallint, geometry) does not exist
LINE 1: SELECT getNearestRoadPlaceId(poi_partition, bbox)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT getNearestRoadPlaceId(poi_partition, bbox)
CONTEXT:  PL/pgSQL function find_parent_for_poi(character,bigint,smallint,geometry,text,text,boolean) line 82 at SQL statement
PL/pgSQL function placex_update() line 178 at assignment


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/nominatim-3-5-1/Nominatim-3.5.1/nominatim/nominatim.py", line 370, in <module>
    Indexer(options).run()
  File "/srv/nominatim-3-5-1/Nominatim-3.5.1/nominatim/nominatim.py", line 210, in run
    self.index(RankRunner(rank))
  File "/srv/nominatim-3-5-1/Nominatim-3.5.1/nominatim/nominatim.py", line 259, in index
    thread = next(next_thread)
  File "/srv/nominatim-3-5-1/Nominatim-3.5.1/nominatim/nominatim.py", line 300, in find_free_thread
    if thread.is_done():
  File "/srv/nominatim-3-5-1/Nominatim-3.5.1/nominatim/nominatim.py", line 187, in is_done
    except psycopg2.errors.DeadlockDetected:
AttributeError: module 'psycopg2' has no attribute 'errors'
Error: 1

```

**Comment by lonvia** [comment]
Please update the functions as per migration guide here: https://nominatim.org/release-docs/develop/admin/Migration/#340-350

I need to backport that section to the 3.5.1 docs.

**Comment by lonvia** [comment]
Now the 3.5.1 documentation has the section as well.
