### ISSUE TITLE
Upgrade issue 3.5->3.6

### ISSUE THREAD

**Issue by ajaybhargav** [osm-search/Nominatim#2163]
**Describe the bug**
Update fails after upgrading from 3.5 to 3.6.

```
nominatim@server:~/Nominatim/build$ ./utils/update.php --import-osmosis-all
2021-02-06 15:23:08: Using project directory: /home/nominatim/Nominatim/build
Traceback (most recent call last):
  File "/home/nominatim/Nominatim/build/nominatim", line 15, in <module>
    phpcgi_path='/usr/bin/php-cgi'))
  File "/home/nominatim/Nominatim/nominatim/cli.py", line 938, in nominatim
    return parser.run(**kwargs)
  File "/home/nominatim/Nominatim/nominatim/cli.py", line 98, in run
    return args.command.run(args)
  File "/home/nominatim/Nominatim/nominatim/cli.py", line 385, in run
    return UpdateReplication._update(args)
  File "/home/nominatim/Nominatim/nominatim/cli.py", line 338, in _update
    state = replication.update(conn, params)
  File "/home/nominatim/Nominatim/nominatim/tools/replication.py", line 90, in update
    last_since_update = dt.datetime.now(dt.timezone.utc) - startdate
TypeError: can't subtract offset-naive and offset-aware datetimes
```
I got rid of above error if I install python 3.7. But then I start getting Psycopg2 error, even though python3-psycopg2 is already installed.
```
nominatim@server:~/Nominatim/build$ ./utils/update.php --import-osmosis-all
Traceback (most recent call last):
  File "/home/nominatim/Nominatim/build/nominatim", line 9, in <module>
    from nominatim import cli
  File "/home/nominatim/Nominatim/nominatim/cli.py", line 15, in <module>
    from .tools.exec_utils import run_legacy_script, run_api_script, run_php_server
  File "/home/nominatim/Nominatim/nominatim/tools/exec_utils.py", line 10, in <module>
    from psycopg2.extensions import parse_dsn
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ModuleNotFoundError: No module named 'psycopg2._psycopg'

```

**To Reproduce**
Update from 3.5 to 3.6

**Software Environment (please complete the following information):**
- Nominatim version: 3.6.0
- Postgresql version: 10
- Postgis version: 2.4.3
- OS: Ubuntu 18.04

**Hardware Configuration (please complete the following information):**
- RAM: 4G
- number of CPUs: 1
- type and size of disks: SSD
- bare metal/AWS/other cloud service:  other

**Postgresql Configuration:**

**Additional context**

**Comment by lonvia** [comment]
This looks like you are upgrading to recent master, not 3.6. There are [migration instructions for 3.6 -> master](https://nominatim.org/release-docs/develop/admin/Migration/#360-master) but at this point I can't recommend using master, at least not for production. We are in the middle of a big restructuring of code and there is no guarantee that master is without bugs or issues.
