### ISSUE TITLE
Nominatim v3.7.0 docs say python 3.5 is supported, but 3.7 is required

### ISSUE THREAD

**Issue by rory** [osm-search/Nominatim#2292]
**Describe the bug**

The code uses the python function [`datetime.fromisoformat`](https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat), which was introduced in python 3.7. However the [documention](https://github.com/osm-search/Nominatim/blob/v3.7.0/docs/admin/Installation.md) says that python 3.5 is supported.

**To Reproduce**
* Try to install with python 3.6 (the latest available on ubuntu bionic 18.04), and do an import, and you get this output:

```
Apr 22 20:36:27 server import-data.sh[42300]: 2021-04-22 20:36:27: Done 1291602/1291602 in 196 @ 6586.315 per second - FINISHED postcodes (location_postcode)
Apr 22 20:38:37 server import-data.sh[42300]: 2021-04-22 20:38:37: Post-process tables
Apr 22 23:53:24 server import-data.sh[42300]: 2021-04-22 23:53:24: Create search index for default country names.
Apr 22 23:53:32 server import-data.sh[42300]: 2021-04-22 23:53:32: Setup website at /srv/nominatim/Nominatim/build/website
Apr 22 23:53:33 server import-data.sh[42300]: 2021-04-22 23:53:33: Cannot determine date of database: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

`init-updates` fails with:
```
Apr 23 00:10:39 server import-data.sh[42300]: + sudo -u nominatim ./utils/update.php --init-updates
Apr 23 00:10:39 server sudo[13982]:     root : TTY=unknown ; PWD=/srv/nominatim/Nominatim/build ; USER=nominatim ; COMMAND=./utils/update.php --init-updates
Apr 23 00:10:39 server sudo[13982]: pam_unix(sudo:session): session opened for user nominatim by (uid=0)
Apr 23 00:10:40 server import-data.sh[42300]: 2021-04-23 00:10:40: Using project directory: /srv/nominatim/Nominatim/build
Apr 23 00:10:40 server import-data.sh[42300]: 2021-04-23 00:10:40: Initialising replication updates
Apr 23 00:10:40 server import-data.sh[42300]: Traceback (most recent call last):
Apr 23 00:10:40 server import-data.sh[42300]:   File "/srv/nominatim/Nominatim/build/nominatim", line 17, in <module>
Apr 23 00:10:40 server import-data.sh[42300]:     phpcgi_path=''))
Apr 23 00:10:40 server import-data.sh[42300]:   File "/srv/nominatim/Nominatim/nominatim/cli.py", line 288, in nominatim
Apr 23 00:10:40 server import-data.sh[42300]:     return parser.run(**kwargs)
Apr 23 00:10:40 server import-data.sh[42300]:   File "/srv/nominatim/Nominatim/nominatim/cli.py", line 92, in run
Apr 23 00:10:40 server import-data.sh[42300]:     return args.command.run(args)
Apr 23 00:10:40 server import-data.sh[42300]:   File "/srv/nominatim/Nominatim/nominatim/clicmd/replication.py", line 147, in run
Apr 23 00:10:40 server import-data.sh[42300]:     return UpdateReplication._init_replication(args)
Apr 23 00:10:40 server import-data.sh[42300]:   File "/srv/nominatim/Nominatim/nominatim/clicmd/replication.py", line 55, in _init_replication
Apr 23 00:10:40 server import-data.sh[42300]:     replication.init_replication(conn, base_url=args.config.REPLICATION_URL)
Apr 23 00:10:40 server import-data.sh[42300]:   File "/srv/nominatim/Nominatim/nominatim/tools/replication.py", line 27, in init_replication
Apr 23 00:10:40 server import-data.sh[42300]:     date = status.compute_database_date(conn)
Apr 23 00:10:40 server import-data.sh[42300]:   File "/srv/nominatim/Nominatim/nominatim/db/status.py", line 39, in compute_database_date
Apr 23 00:10:40 server import-data.sh[42300]:     return dt.datetime.fromisoformat(match[1]).replace(tzinfo=dt.timezone.utc)
Apr 23 00:10:40 server import-data.sh[42300]: AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

**Software Environment (please complete the following information):**
- Nominatim version: 3.7.0
- Python version: 3.6.9 (latest from ubuntu)
- Postgis version: 2.4.3
- OS: Ubuntu 18.04 bionic

**Comment by lonvia** [comment]
Fix is now available in the just released 3.7.1.
