### ISSUE TITLE
Importing into an external postgres database - calculate postcodes error

### ISSUE THREAD

**Issue by lonvia** [osm-search/Nominatim#2380]
### Discussed in https://github.com/osm-search/Nominatim/discussions/2378

<div type='discussions-op-text'>

<sup>Originally posted by **welshstew** June 29, 2021</sup>
Hello folks :wave: ,

I'm trying to import data into an external postgres database, it progresses to a point but fails on calculate postcodes.  Is there something I am missing here?  Any help gratefully received.

(very new to Nominatim, so have been following the docs, but stuck on this now :( )

psql (PostgreSQL) 12.7
nominatim 3.7

The .env file in my project directory is:
```
# .env
# Default configuration settings for Nominatim.
# This file uses the dotenv format.
NOMINATIM_DATABASE_DSN="pgsql:dbname=monaco;user=postgres;password=rootyroot;host=localhost;port=15432"
NOMINATIM_DATABASE_MODULE_PATH="/opt/app-root/src/build/module/"
```
and I am getting the error:

```
...
2021-06-29 16:07:25: Load data into placex table
 count 
-------
  1795
(1 row)

 count 
-------
    66
(1 row)

...

2021-06-29 16:07:30: Calculate postcodes
2021-06-29 15:07:30 == Calculate Postcodes
ERROR: pgsql returned with error code (1)
string(34) "pgsql returned with error code (1)"
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 17, in <module>
    phpcgi_path='/usr/bin/php-cgi'))
  File "/usr/local/lib64/nominatim/lib-python/nominatim/cli.py", line 288, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib64/nominatim/lib-python/nominatim/cli.py", line 92, in run
    return args.command.run(args)
  File "/usr/local/lib64/nominatim/lib-python/nominatim/clicmd/setup.py", line 120, in run
    nominatim_env=args, throw_on_fail=not args.ignore_errors)
  File "/usr/local/lib64/nominatim/lib-python/nominatim/tools/exec_utils.py", line 33, in run_legacy_script
    check=throw_on_fail)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/env', 'php', '-Cq', '/usr/local/lib64/nominatim/lib-php/admin/setup.php', '--calculate-postcodes']' returned non-zero exit status 255.
```
</div>

**Comment by lonvia** [comment]
This is a CentOS-specific issue and has to do with the way PHP is configured. In CentOS the environment is not handed in as a variable by default but [that specific piece of code depends on exactly that](https://github.com/osm-search/Nominatim/blob/b51efd876fd29aa42037c17aeb93db6297c79172/lib-php/Shell.php#L36). So the workaround here is to change your `/etc/php.ini`:

```
- variables_order = "GPCS"
+ variables_order = "EGPCS"
```
This will cause the necessary `$_ENV` variable to be created.

That's not ideal but given that we are moving away from PHP and the affected code has already been removed on master, I'd rather prefer to declare this as a `wont-fix` on the Nominatim side..
