### ISSUE TITLE
Nominatim upgrade from 3.6 to 3.7.2 problem after check database and db-postprocess

### ISSUE THREAD

**Issue by jinzo** [osm-search/Nominatim#2451]
**Describe the bug**
I updated my Nominatim install from 3.6 to 3.7.2, checked the database, created some indexes and encountered a problem. I think the command log sequence will be the most explanatory:
```
nominatim@bennu:~/nominatim-project$ nominatim admin --check-database
2021-09-25 14:54:48: Using project directory: /srv/nominatim/nominatim-project
2021-09-25 14:54:48: Checking database
Checking database connection ... OK
Checking for placex table ... OK
Checking for placex content ... OK
Checking that nominatim.so module is installed ... OK
Checking indexing status ... Failed
The indexing didn't finish. 3756 entries are not yet indexed.

To index the remaining entries, run:   nominatim index

Checking that database indexes are complete ... Failed
           The following indexes are missing:
             idx_placex_housenumber
idx_osmline_parent_osm_id_with_hnr

           Rerun the index creation with:   nominatim import --continue db-postprocess

Checking that all database indexes are valid ... OK
Checking TIGER external data table. ... not applicable
nominatim@bennu:~/nominatim-project$ nominatim index
<snip, log, finished all ok>
nominatim@bennu:~/nominatim-project$ nominatim admin --check-database
2021-09-25 14:55:34: Using project directory: /srv/nominatim/nominatim-project
2021-09-25 14:55:34: Checking database
Checking database connection ... OK
Checking for placex table ... OK
Checking for placex content ... OK
Checking that nominatim.so module is installed ... OK
Checking indexing status ... OK
Checking that database indexes are complete ... Failed
           The following indexes are missing:
             idx_placex_housenumber
idx_osmline_parent_osm_id_with_hnr

           Rerun the index creation with:   nominatim import --continue db-postprocess

Checking that all database indexes are valid ... OK
Checking TIGER external data table. ... not applicable
nominatim@bennu:~/nominatim-project$ nominatim import --continue db-postprocess
2021-09-25 14:55:49: Using project directory: /srv/nominatim/nominatim-project
2021-09-25 14:55:49: Post-process tables
2021-09-25 14:58:07: Create search index for default country names.
2021-09-25 14:58:11: Setup website at /srv/nominatim/nominatim-project/website
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 11, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 288, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 92, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 151, in run
    properties.set_property(conn, 'database_version',
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/properties.py", line 9, in set_property
    cur.execute('SELECT value FROM nominatim_properties WHERE property = %s',
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/connection.py", line 26, in execute
    super().execute(query, args)
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 142, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.errors.UndefinedTable: relation "nominatim_properties" does not exist
LINE 1: SELECT value FROM nominatim_properties WHERE property = 'dat...
                          ^

nominatim@bennu:~/nominatim-project$ nominatim admin --check-database
2021-09-25 15:00:18: Using project directory: /srv/nominatim/nominatim-project
2021-09-25 15:00:18: Checking database
Checking database connection ... OK
Checking for placex table ... OK
Checking for placex content ... OK
Checking that nominatim.so module is installed ... OK
Checking indexing status ... OK
Checking that database indexes are complete ... OK
Checking that all database indexes are valid ... OK
Checking TIGER external data table. ... not applicable
```

**Software Environment (please complete the following information):**
- Nominatim version: 3.7.2
- Postgresql version: 12+214ubuntu0.1
- Postgis version: 3.0.0+dfsg-6ubuntu4
- OS: Ubuntu 20.04

All in all I'm not even sure this is a real issue or not, as everything seems to work for now - but decided it cannot hurt to report this.
P.S: Thanks for this amazing software!

QUICKEDIT: Could this be because I have the nominatim-ui currently installed outside of this project

NOT SO QUICK EDIT:
Looks like I have some bigger problems, not sure if I missed something or not as I went thorough the documentation multiple times.
First thing I was missing modules/nominatim.so in my project directory (so nominatim refresh did not work) - this is something that has been nagging me quite some time, shouldn't I init the project somehow? After I copied the modules/nominatim.so from the build directory I tried to init replication and start it but encountered new problem
```
nominatim@bennu:~/nominatim-project$ nominatim refresh --functions
2021-09-25 15:35:37: Using project directory: /srv/nominatim/nominatim-project
2021-09-25 15:35:37: Create functions
nominatim@bennu:~/nominatim-project$ nominatim replication --init
2021-09-25 15:35:55: Using project directory: /srv/nominatim/nominatim-project
2021-09-25 15:35:55: Initialising replication updates
2021-09-25 15:35:56: Updates intialised at sequence 3103 (2021-09-24 17:20:38+00:00)
2021-09-25 15:35:56: Create functions
nominatim@bennu:~/nominatim-project$ nominatim replication
2021-09-25 15:36:28: Using project directory: /srv/nominatim/nominatim-project
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 11, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 288, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 92, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 154, in run
    UpdateReplication._update(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 113, in _update
    state = replication.update(conn, params)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/replication.py", line 95, in update
    last_since_update = dt.datetime.now(dt.timezone.utc) - startdate
TypeError: can't subtract offset-naive and offset-aware datetimes

```
So everything points to a direction that I have a not-up-to-date DB structure?

**Comment by lonvia** [comment]
Have you run the database migration as described in https://nominatim.org/release-docs/latest/admin/Migration/ ?

**Comment by jinzo** [comment]
I'm not sure how I missed this, but I did start the migration a few minutes ago. 
```
nominatim@bennu:~/nominatim-project$ nominatim admin --migrate
2021-09-25 15:41:17: Using project directory: /srv/nominatim/nominatim-project
2021-09-25 15:41:17: Checking for necessary database migrations
2021-09-25 15:41:17: Runnning:  Add timezone to timestamp in status table. (3.5.0-99)
2021-09-25 15:41:17: Runnning:  Install database module in project directory. (3.5.0-99)
2021-09-25 15:41:17: Runnning:  Add nominatim_property table. (3.5.0-99)
2021-09-25 15:41:17: Runnning:  Transliterate housenumbers. (3.6.0-0)
```

Another interesting point is that I'm quite sure that I set up this project with Nominatim 3.6 initially and this is my first upgrade, so not sure why a 3.5.0-99 migration is running. But maybe that's ok from the context :)
From what I can see, this copied the .so file too, which is great! Hopefully I did not put the db state in an unrecoverable position with my index and db-postprocess commands.

Sorry for not noticing this before and thanks for your help, will report back when the command finishes.

**Comment by lonvia** [comment]
3.5.0-99 just means that the migration code detected a version that is from before automatic migrations existed. It's bootstrapping itself before doing the actual migration. All normal.

**Comment by jinzo** [comment]
Thanks for the info and tip - I can confirm that after running the migration everything works as expected.
