### ISSUE TITLE
nominatim import XML parsing error

### ISSUE THREAD

**Issue by convolutionbbs** [osm-search/Nominatim#2623]
Hello,
I've been following the guide: https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-20/

I am at the point of performing the import (doing the most recent global planet file):
nominatim import --osm-file /media/4tb_ssd/files/planet-220214.osm.bz2 2>&1 | tee setup.log

It errors out here (twice - I manually deleted the nominatim database in psql before the second try):

Relation(9655020 10727.8/s)2022-03-04 21:24:45  ERROR: XML parsing error at line 21710386681, column 2: unclosed token
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 11, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 235, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 96, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 77, in run
    database_import.import_osm_data(files,
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/database_import.py", line 98, in import_osm_data
    run_osm2pgsql(options)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/exec_utils.py", line 139, in run_osm2pgsql
    subprocess.run(cmd, cwd=options.get('cwd', '.'),
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/lib/nominatim/osm2pgsql', '--hstore', '--latlon', '--slim', '--with-forward-dependencies', 'false', '--log-progress', 'true', '--number-processes', '1', '--cache', '94314', '--output', 'gazetteer', '--style', '/usr/local/etc/nominatim/import-extratags.style', '--create', '/media/4tb_ssd/files/planet-220214.osm.bz2']' returned non-zero exit status 1.

Is this an error with the planet file or something with the software (or something I did)?  Should I wait for the next planet file to try another import?

Thanks.

**Comment by lonvia** [comment]
Looks like your planet file is corrupted. Have you checked against the checksum? That said, you really should be using PBF files instead of XML.
