### ISSUE TITLE
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "parent" when trying to import

### ISSUE THREAD

**Issue by jhrvalente** [osm-search/Nominatim#2942]
I had created an empty database called nominatim on my DB cluster, pointed the DSN to my database with the dbname, host, port, user and pass and tried to import the map of Portugal with the following params:

```
nohup <path/to/file>/build/utils/setup.php \
 --threads 4 \
 --setup-db \
 --import-data \
 --create-functions \
 --enable-diff-updates \
 --enable-debug-statements \
 --create-tables \
 --create-partition-tables \
 --create-partition-functions \
 --import-wikipedia-articles \
 --load-data \
 --import-tiger-data \
 --calculate-postcodes \
 --index \
 --index-noanalyse \
 --create-search-indices \
 --create-country-names \
 --osm-file <path/to/file>/portugal-latest.osm.pbf >> <path/to/file>/logImportPortugal.txt 2>&1
 ```
 
 But it is giving me the following error:
 
 ```
 WARNING: Starting rank 25
Traceback (most recent call last):
  File "/srv/nominatim/Nominatim-3.5.1/nominatim/nominatim.py", line 370, in <module>
    Indexer(options).run()
  File "/srv/nominatim/Nominatim-3.5.1/nominatim/nominatim.py", line 215, in run
    self.index(RankRunner(self.maxrank))
  File "/srv/nominatim/Nominatim-3.5.1/nominatim/nominatim.py", line 259, in index
    thread = next(next_thread)
  File "/srv/nominatim/Nominatim-3.5.1/nominatim/nominatim.py", line 300, in find_free_thread
    if thread.is_done():
  File "/srv/nominatim/Nominatim-3.5.1/nominatim/nominatim.py", line 178, in is_done
    if self.conn.poll() == psycopg2.extensions.POLL_OK:
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "parent"
LINE 1: parent.place_id
        ^
QUERY:  parent.place_id
CONTEXT:  PL/pgSQL function find_parent_for_address(text,text,smallint,geometry) line 25 at RAISE
PL/pgSQL function find_parent_for_poi(character,bigint,smallint,geometry,text,text,boolean) line 31 at assignment
PL/pgSQL function placex_update() line 178 at assignment

ERROR: error status 1 running nominatim!
string(33) "error status 1 running nominatim!"
```

The flag --setup-db shouldn't create all the relations? What am I missing?

**Comment by mtmail** [comment]
Since this is a new installation, can you try the latest Nominatim release (4.2.0)? https://nominatim.org/release-docs/latest/admin/Installation/

**Comment by jhrvalente** [comment]
Yes, I know I dont need Tiger for Portugal, I just used the same command that I am using for other import with the same params.
On the machine I am working, they already have a folder with the src compiled for nominatim but I will try to create another folder for nominatim with version 4.2.0 and give it a try
