### ISSUE TITLE
Support External DB

### ISSUE THREAD

**Issue by sebheitzmann** [osm-search/Nominatim#2973]
**Describe the bug**

Is the external database supported ?

When i try to import data with an external database a lot of things are missing.

The code assume that a createdb is an existing local command. I've corrected this but after that there is a psql command
 
**To Reproduce**

run import with 

nominatim import --osm-file /data/data.osm.pbf

**Software Environment (please complete the following information):**
- Nominatim version: 4.2
- Postgresql version: postgis15
- Postgis version:
- OS: linux

**Comment by sebheitzmann** [comment]
root@9cc37a485860:/app# nominatim import --osm-file /data/data.osm.pbf 
2023-02-08 04:35:32: Using project directory: /app
2023-02-08 04:35:33: Creating database
2023-02-08 04:35:33: Setting up country tables
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 14, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/setup.py", line 89, in run
    country_info.setup_country_tables(args.config.get_libpq_dsn(),
  File "/usr/local/lib/nominatim/lib-python/nominatim/data/country_info.py", line 118, in setup_country_tables
    db_utils.execute_file(dsn, sql_dir / 'country_osm_grid.sql.gz')
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/utils.py", line 51, in execute_file
    with subprocess.Popen(cmd, env=get_pg_env(dsn), stdin=subprocess.PIPE) as proc:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child

**Comment by lonvia** [comment]
The connection information is handed to createdb via [PG environment variables](https://www.postgresql.org/docs/current/libpq-envars.html). There is no real reason that should not work with external databases. Have you tried on the command line?

The real fix for this is a non-privileged import mode, where you create your database externally and Nominatim just imports into it.  It's somewhere on the list (see #2719) but not very high at the moment.

**Comment by sebheitzmann** [comment]
createdb is an (admin/server ? ) postgresql command, I don't have this command on the nominatim server.

**Comment by mtmail** [comment]
In that case you need to install it on your nominatim server. https://nominatim.org/release-docs/latest/admin/Installation/#prerequisites The database can still be on another server of course.

**Comment by sebheitzmann** [comment]
You mean that i can connect to another server if i have a local server ? Strange behavior ...

**Comment by sebheitzmann** [comment]
https://manpages.debian.org/testing/postgresql-client-12/createuser.1.en.html

It seams that th createdb command is in the postgresql client. So it's logical. 

My Bad
