### ISSUE TITLE
Interpolation lines indexing raises `psycopg2.errors.InternalError_`

### ISSUE THREAD

**Issue by vittorio-dealroom** [osm-search/Nominatim#2989]
**Describe the bug**

I run
```
nominatim index --threads 15
```
and right after it starts processing the interpolation lines -- so right after stdout is `Starting interpolation lines (location_property_osmline) (using batch size 20)` -- I get this traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 14, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/index.py", line 58, in run
    indexer.index_by_rank(args.minrank, args.maxrank)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 178, in index_by_rank
    total += self._index(runners.InterpolationRunner(analyzer), 20)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 222, in _index
    with WorkerPool(self.dsn, self.num_threads) as pool:
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 235, in __exit__
    self.finish_all()
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 185, in finish_all
    thread.wait()
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 128, in wait
    wait_select(self.conn)
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 762, in wait_select
    state = conn.poll()
psycopg2.errors.InternalError_: line_substring: 1st arg isn't a line
CONTEXT:  PL/pgSQL function osmline_update() line 113 at assignment
```

**To Reproduce**

I have continuous updates running on the VM as a systemd service (I followed [this guide](https://nominatim.org/release-docs/latest/admin/Update/#continuous-updates)).

Since (and including) the update from February 26 from https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/replication/day/000/003/ I encounter this issue anytime I run the indexing process. The update itself from February 26 (and subsequent ones) always stops at this point, with the same traceback.

**Software Environment (please complete the following information):**
- Nominatim version: 4.2.0-0
- Postgresql version: 14.6
- Postgis version: 3.2 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
- OS: Ubuntu 22.04.1

**Hardware Configuration (please complete the following information):**
- RAM: 16.5GB
- number of CPUs: 8
- type and size of disks: 2048GB SSD
- bare metal/AWS/other cloud service: GCP

**Postgresql Configuration:**

```
max_connections = 250
shared_buffers = 4GB
effective_cache_size = 12GB
maintenance_work_mem = 1GB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 4194kB
min_wal_size = 1GB
max_wal_size = 4GB
max_worker_processes = 8
max_parallel_workers_per_gather = 4
max_parallel_workers = 8
max_parallel_maintenance_workers = 4
```

**Additional context**

As per DEBUG-level output, the `part` that is being processed when the exception is raised is:
```
Processing places: [[142746619, {'street': '3', 'inclusion': 'actual', '_inherited': '', 'housenumber': '800', 'interpolation': 'even'}], [142746628, {'street': '3', 'inclusion': 'actual', '_inherited': '', 'housenumber': '801', 'interpolation': 'odd'}], [142746850, {'street': '3', 'inclusion': 'actual', '_inherited': '', 'housenumber': '900', 'interpolation': 'even'}], [142746860, {'street': '3', 'inclusion': 'actual', '_inherited': '', 'housenumber': '999', 'interpolation': 'odd'}], [142746971, {'street': '3', 'inclusion': 'actual', '_inherited': '', 'housenumber': '1000', 'interpolation': 'even'}], [142746981, {'street': '3', 'inclusion': 'actual', '_inherited': '', 'housenumber': '1001', 'interpolation': 'odd'}], [315575611, {'city': 'Sondershausen', 'street': 'Martin-Andersen-Nexö-Straße', 'country': 'DE', 'postcode': '99706', '_inherited': '', 'housenumber': '4', 'interpolation': 'even'}], [315579078, {'street': 'Via Arziglia', 'interpolation': 'odd'}], [315579079, {'street': 'Via Arziglia', 'interpolation': 'odd'}], [315579080, {'street': 'Via Arziglia', 'interpolation': 'odd'}], [315579081, {'street': 'Via Arziglia', 'interpolation': 'odd'}], [315579082, {'street': 'Via Arziglia', 'interpolation': 'odd'}], [315579083, {'street': 'Via Arziglia', 'interpolation': 'odd'}], [350893064, {'city': 'Zapala', 'street': 'Avenida 12 de Julio', 'country': 'AR', 'interpolation': 'odd'}], [350962345, {'city': 'Zapala', 'street': 'Avenida 12 de Julio', 'country': 'AR', 'interpolation': 'odd'}], [350962346, {'city': 'Zapala', 'street': 'Avenida 12 de Julio', 'country': 'AR', 'interpolation': 'odd'}], [350962347, {'city': 'Zapala', 'street': 'Avenida 12 de Julio', 'country': 'AR', 'interpolation': 'odd'}], [350962348, {'city': 'Zapala', 'street': 'Avenida 12 de Julio', 'country': 'AR', 'interpolation': 'even'}], [350962349, {'city': 'Zapala', 'street': 'Avenida 12 de Julio', 'country': 'AR', 'interpolation': 'even'}], [350990509, {'city': 'Zapala', 'street': 'Avenida Avellaneda', 'country': 'AR', 'interpolation': 'odd'}]]
```
but other times it is different.

This is the last query (DEBUG-level output):
```
SELECT word_id FROM word WHERE word_token = 'avenida avellaneda' and type = 'W'
```

---
Thank you!

**Comment by lonvia** [comment]
Have you imported the database with 4.2.0 or did you do this with an earlier version and only upgraded the software recently?

**Comment by vittorio-dealroom** [comment]
Thanks for answering! The database was imported with 4.2.0. Also, the continuous updates and indexing had been working fine before Sunday.

**Comment by lonvia** [comment]
There were no problems on our production servers, so this needs a bit more debugging from your side, I'm afraid.

Your debug output for `part` has place_ids for the 20 candidates for the breakage already. That's the first number in the inner arrays, i.e. 142746619, 142746628, ... First step is to find the one causing trouble. Please run the following for each of the ids: `BEGIN; UPDATE location_property_osmline SET indexed_status = 0 WHERE place_id = <place_id>; ROLLBACK;`

This should fail for on of the IDs with the error you see above. Now please provide the output of:
`SELECT place_id, osm_id, startnumber, endnumber, step, address, ST_AsText(linegeo) FROM location_property_osmline WHERE place_id = <place_id>`

**Comment by vittorio-dealroom** [comment]
The problematic one is `place_id = 315575611`. The query:
```
SELECT place_id, osm_id, startnumber, endnumber, step, address, ST_AsText(linegeo) FROM location_property_osmline WHERE place_id = 315575611;
```
returns:
```
 place_id  |  osm_id   | startnumber | endnumber | step |         address         |                        st_astext
-----------+-----------+-------------+-----------+------+-------------------------+---------------------------------------------------------
 315575611 | 146450492 |             |        40 |    2 | "interpolation"=>"even" | LINESTRING(10.8854497 51.3618539,10.8857703 51.3616287)
(1 row)
```

**Comment by lonvia** [comment]
The empty startnumber field clearly shouldn't be there. Can you please provide the output of the following additional queries:

* `SELECT place_id, osm_id, startnumber, endnumber, indexed_date, ST_AsText(linegeo) FROM location_property_osmline WHERE osm_id = 146450492;`
* `SELECT nodes FROM planet_osm_ways WHERE id = 146450492`
* `SELECT osm_id, address, indexed_date, ST_AsText(geometry) FROM placex, planet_osm_ways WHERE osm_type = 'N' and osm_id = any(nodes) and id = 146450492`

I hope that is enough information for me to track down the bug. So once you have done this, you can fix your database by simply deleting the bad interpolation: `DELETE FROM location_property_osmline WHERE osm_id = 146450492`. If you want to have the data back, first finish the indexing with `nominatim --index` and then readd the interpolation with `nominatim add-data --way 146450492`. Run indexing again. Afterwards all should be back to normal and you can resume updates.

**Comment by vittorio-dealroom** [comment]
Queries outputs:

```
nominatim=# SELECT place_id, osm_id, startnumber, endnumber, indexed_date, ST_AsText(linegeo) FROM location_property_osmline WHERE osm_id = 146450492;

 place_id  |  osm_id   | startnumber | endnumber |        indexed_date        |                        st_astext
-----------+-----------+-------------+-----------+----------------------------+---------------------------------------------------------
 315575611 | 146450492 |             |        40 | 2023-02-11 08:25:26.444625 | LINESTRING(10.8854497 51.3618539,10.8857703 51.3616287)
```

```
nominatim=# SELECT nodes FROM planet_osm_ways WHERE id = 146450492;

                                                                                            nodes
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 {1597396882,776511280,1597396909,10693597129,1597396932,1597396859,1597396860,1597396941,2196001186,1597396857,1597396862,2196052378,1597396937,1597396926,1597396858,1597396872,1597396922}
(1 row)
```

```
nominatim=# SELECT osm_id, address, indexed_date, ST_AsText(geometry) FROM placex, planet_osm_ways WHERE osm_type = 'N' and osm_id = any(nodes) and id = 146450492;

   osm_id   |                                                           address                                                           |        indexed_date        |          st_astext
------------+-----------------------------------------------------------------------------------------------------------------------------+----------------------------+------------------------------
  776511280 | "city"=>"Sondershausen", "street"=>"Martin-Andersen-Nexö-Straße", "country"=>"DE", "postcode"=>"99706", "housenumber"=>"4"  | 2023-02-26 06:43:59.554453 | POINT(10.8846902 51.3624555)
 1597396858 | "city"=>"Sondershausen", "street"=>"Martin-Andersen-Nexö-Straße", "country"=>"DE", "postcode"=>"99706", "housenumber"=>"66" | 2023-02-26 06:43:59.554453 | POINT(10.8935507 51.3598419)
 1597396862 | "city"=>"Sondershausen", "street"=>"Martin-Andersen-Nexö-Straße", "country"=>"DE", "postcode"=>"99706", "housenumber"=>"42" | 2023-02-26 06:43:59.554453 | POINT(10.8898413 51.3605923)
 1597396872 | "city"=>"Sondershausen", "street"=>"Martin-Andersen-Nexö-Straße", "country"=>"DE", "postcode"=>"99706", "housenumber"=>"72" | 2023-02-26 06:43:59.554453 | POINT(10.8951117 51.3595004)
 1597396882 | "city"=>"Sondershausen", "street"=>"Martin-Andersen-Nexö-Straße", "country"=>"DE", "postcode"=>"99706", "housenumber"=>"2"  | 2023-02-26 06:43:59.554453 | POINT(10.8844288 51.3626807)
 1597396922 | "city"=>"Sondershausen", "street"=>"Martin-Andersen-Nexö-Straße", "country"=>"DE", "postcode"=>"99706", "housenumber"=>"92" | 2023-02-26 06:43:59.554453 | POINT(10.8975038 51.3590034)
 1597396926 | "city"=>"Sondershausen", "street"=>"Martin-Andersen-Nexö-Straße", "country"=>"DE", "postcode"=>"99706", "housenumber"=>"62" | 2023-02-26 06:43:59.554453 | POINT(10.8921881 51.3599995)
 1597396941 | "city"=>"Sondershausen", "street"=>"Martin-Andersen-Nexö-Straße", "country"=>"DE", "postcode"=>"99706", "housenumber"=>"28" | 2023-02-26 06:43:59.554453 | POINT(10.8873556 51.3610146)
(8 rows)
```

-----

I noticed that if I do `curl --location "http://localhost/details?place_id=350990509&format=json"` I get a 404. But if I do `curl --location "http://localhost/details?osmid=146450492&osmtype=W&format=json"` I get that `place_id = 143234813`.

I don't know if this is relevant, I thought worth including it here.

**Comment by vittorio-dealroom** [comment]
I deleted the faulty rows and re-added the OSM objects, indexing works well now. Thank you!

**Comment by lonvia** [comment]
This looks like a setup error on your side. Nominatim can't correctly retrieve the geometry for the interpolation. This normally happens, when you have used a flatnode file for the import and then removed the flatnode file or forgot to configure it for your updates.
