### ISSUE TITLE
 Splitting of Point geometries is unsupported error still exists in 4.2.3

### ISSUE THREAD

**Issue by rj45-2** [osm-search/Nominatim#3036]
Today encountered surprise (I thought this is fixed in latest version).

2023-04-20 18:06:53: Starting interpolation lines (location_property_osmline) (using batch size 20)
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 14, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 196, in run
    self._update(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 161, in _update
    indexer.index_full(analyse=False)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 140, in index_full
    if self.index_by_rank(26, 30) > 1000:
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 178, in index_by_rank
    total += self._index(runners.InterpolationRunner(analyzer), 20)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 222, in _index
    with WorkerPool(self.dsn, self.num_threads) as pool:
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 235, in __exit__
    self.finish_all()
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 185, in finish_all
    thread.wait()
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 128, in wait
    wait_select(self.conn)
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 762, in wait_select
    state = conn.poll()
**psycopg2.errors.InternalError_: Splitting of Point geometries is unsupported**
CONTEXT:  PL/pgSQL function osmline_update() line 77 at assignment

Dug into it (status 1 is error):

nominatim=# SELECT place_id, indexed_status FROM location_property_osmline WHERE indexed_status = 1;
 place_id  | indexed_status
-----------+----------------
  22307776 |              1
  28938533 |              1
  12577820 |              1
  12577834 |              1
  12577827 |              1
  12577812 |              1
 312481190 |              1
  12577838 |              1
  20129153 |              1
  17709887 |              1
  28938522 |              1
(11 rows)

env looks like:

NOMINATIM_FLATNODE_FILE="/srv/nominatim/nominatim-planet/flatnode.file"
# base URL of the replication service
NOMINATIM_REPLICATION_URL="https://planet.openstreetmap.org/replication/minute/"
# How often upstream publishes diffs (in seconds)
NOMINATIM_REPLICATION_UPDATE_INTERVAL=75
# How long to sleep if no update found yet (in seconds)
NOMINATIM_REPLICATION_RECHECK_INTERVAL=60
NOMINATIM_USE_US_TIGER_DATA=yes
NOMINATIM_LOG_DB=no
NOMINATIM_REPLICATION_MAX_DIFF=1
# NOMINATIM_LOG_FILE=/var/log/_nominatim_debug.log

Now we have to delete ids manually and reindex as usual..

**Comment by rj45-2** [comment]
yes, found in history

**Comment by lonvia** [comment]
Then please run `nominatim refresh --functions` and see if that fixes the problem.

**Comment by rj45-2** [comment]
looks like nominatim refresh --functions not found in history, my fault :)
We'll see
BTW , This doc should be appended https://nominatim.org/release-docs/latest/admin/Migration/

**Comment by geoneutrino** [comment]
had to refresh functions too
yes, docs could be updated but maybe in the future nominatim admin migrate / check-database could integrate refresh function too, would be easier ?
