### ISSUE TITLE
Replication fails with python error psycopg2.errors line_substring

### ISSUE THREAD

**Issue by denen99** [osm-search/Nominatim#3038]
**Describe the bug**

When running replication, it repeatedly throws a python error , was working fine. 

**To Reproduce**

Run the replication command nominatim replication --project-dir /srv/nominatim/nominatim-planet/

**Software Environment (please complete the following information):**
- Nominatim version:  4.2.1
- Postgresql version:  14.6
- Postgis version:  3.2
- OS:  Ubuntu 22.04.1

**Hardware Configuration (please complete the following information):**
- RAM:  64GB
- number of CPUs:  10
- type and size of disks:  2TB SSD
- bare metal/AWS/other cloud service:   Contabo XL SSD 

**Postgresql Configuration:**

**Additional context**

Error message

2023-04-22 19:06:53: Starting interpolation lines (location_property_osmline) (using batch size 20)
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 14, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 196, in run
    self._update(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 161, in _update
    indexer.index_full(analyse=False)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 140, in index_full
    if self.index_by_rank(26, 30) > 1000:
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 178, in index_by_rank
    total += self._index(runners.InterpolationRunner(analyzer), 20)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 222, in _index
    with WorkerPool(self.dsn, self.num_threads) as pool:
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 235, in __exit__
    self.finish_all()
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 185, in finish_all
    thread.wait()
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 128, in wait
    wait_select(self.conn)
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 762, in wait_select
    state = conn.poll()
psycopg2.errors.InternalError_: line_substring: 1st arg isn't a line
CONTEXT:  PL/pgSQL function osmline_update() line 113 at assignment

**Comment by mtmail** [comment]
That’s fixed in version 4.2.3. Related https://github.com/osm-search/Nominatim/issues/2989

**Comment by denen99** [comment]
had to run nominate refresh --functions , then it worked with 4.2.3, thank you!
