### ISSUE TITLE
nomimatim problems with replication => psycopg2.errors Splitting of Point geometries is unsupported 

### ISSUE THREAD

**Issue by spark-andreas** [osm-search/Nominatim#3040]
We have a running nominatim/openstreetmap instance.
We have done a full import.
nominatim admin --check-database says all fine

We have successfully done a replication --init
But if we now trigger a update of data after downloading the new data we end up with

2023-04-24 10:10:41: Starting interpolation lines (location_property_osmline) (using batch size 20)
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 14, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 196, in run
    self._update(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 161, in _update
    indexer.index_full(analyse=False)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 140, in index_full
    if self.index_by_rank(26, 30) > 1000:  
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 178, in index_by_rank
    total += self._index(runners.InterpolationRunner(analyzer), 20)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 237, in _index
    LOG.info("Wait time: fetcher: %.2fs,  pool: %.2fs",
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 235, in __exit__
    self.finish_all()
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 185, in finish_all
    thread.wait()
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 128, in wait
    wait_select(self.conn)
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 778, in wait_select
    state = conn.poll()
psycopg2.errors.InternalError_: Splitting of Point geometries is unsupported
CONTEXT:  PL/pgSQL function osmline_update() line 77 at assignment

If there is something we are missing here? I can't find anything on the internet or maybe I'm searching wrong?

- Nominatim version: 2.4.3
- Postgresql version: 13
- Postgis version: 3.1.1
- python3-psycopg2: 2.8.6
- OS: Debian 11 (bullseye)

hardware:
- RAM: 128 GB
- number of CPUs: 32
- type and size of disks: 4 TB SSD
- dedicated hosted server

**Comment by mtmail** [comment]
Can you clarify which Nominatim version was used for the initial update and if you migrated to a newer Nomatim version later? (you write 2.4.3 but I'm sure you mean a 4.x.x version).

The issue was supposed to be fixed with Nominatim 4.3.2 but there's another command you'd need to run after the migration. That was reported in https://github.com/osm-search/Nominatim/issues/3036

**Comment by spark-andreas** [comment]
nominatim refresh --functions fixes my problem too.

And sorry, you're right. We had the problem with 4.2.2 and 4.2.3 with nominatim refresh --functions seems to fixing it.
