### ISSUE TITLE
Upgrading from 4.1.0 to latest

### ISSUE THREAD

**Issue by Strvm** [osm-search/Nominatim#3236]
Hello, 

I'm trying to upgrade my server (which is currently on version 4.1.0) to one of the latest version of Nominatim).

```json
{
   "status":0,
   "message":"OK",
   "data_updated":"2022-10-24T20:00:00+00:00",
   "software_version":"4.1.0-0"
}
```

When I perform: `nominatim admin --migrate` I get the following error:

```
2023-10-30 09:27:55: Using project directory: /srv/nominatim
2023-10-30 09:27:55: Checking for necessary database migrations
2023-10-30 09:27:55: Running:  Add timezone to timestamp in status table. (3.5.0-99)
2023-10-30 09:27:55: Running:  Add nominatim_property table. (3.5.0-99)
2023-10-30 09:27:55: Running:  Transliterate housenumbers. (3.6.0-0)
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 14, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 264, in nominatim
    return parser.run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 126, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/admin.py", line 71, in run
    return migration.migrate(args.config, args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/migration.py", line 59, in migrate
    func(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/tools/migration.py", line 166, in change_housenumber_transliteration
    cur.execute("DELETE FROM word WHERE class = 'place' and type = 'house'")
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/connection.py", line 36, in execute
    super().execute(query, args)
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 146, in execute
    return super().execute(query, vars)
psycopg2.errors.UndefinedColumn: column "class" does not exist
LINE 1: DELETE FROM word WHERE class = 'place' and type = 'house'
```

I don't see anything mentioning changes to the schema except for the index I need to create https://nominatim.org/release-docs/latest/admin/Migration/ . What should I do?

Thank you

**Comment by mtmail** [comment]
Was the database imported as `--reverse-only`? Can you post the output of `nominatim admin --check-database` ?

**Comment by Strvm** [comment]
> Was the database imported as `--reverse-only`? Can you post the output of `nominatim admin --check-database` ?

Don't think so, I imported it around a year ago with a full planet import and been able to lookup/reverse as I wish. Here is the response you asked for:

```
nominatim@nominatim-1:~$ nominatim admin --check-database
2023-10-30 10:06:07: Using project directory: /srv/nominatim
2023-10-30 10:06:07: Checking database
Checking database connection ... OK
Checking for placex table ... OK
Checking for placex content ... OK
Checking that tokenizer works ... OK
Checking for wikipedia/wikidata data ... OK
Checking indexing status ... OK
Checking that database indexes are complete ... OK
Checking that all database indexes are valid ... OK
Checking TIGER external data table. ... OK
```

**Comment by mtmail** [comment]
Reading `tools/migration.py` I'd expect a `Detected database version` log line to be printed.

I'm guessing you have a `nominatim_properties` table but it's empty?

```sql
SELECT * FROM nominatim_properties;
```

Looks like Nominatim (latest version) needs some logic to account for that.

Try adding the version and rerun the migration

```sql
INSERT INTO nominatim_properties (property, value) VALUES ('database_version', '4.1.0-0');
```

**Comment by Strvm** [comment]
That seems to have fixed it. To upgrade Nominatim, do I have to download the latest release and rebuild it on my server?

nominatim@nominatim:~$ nominatim admin --migrate
2023-10-31 11:31:58: Using project directory: /srv/nominatim
2023-10-31 11:31:58: Checking for necessary database migrations
2023-10-31 11:31:58: Database already at latest version (4.1.0-0)

**Comment by mtmail** [comment]
Yes. Note that the new release might have added more dependencies (basically the apt-get list on https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-22/ or similar).

**Comment by lonvia** [comment]
If your nominatim_properties table existed but was empty, then something is broken with your installation. The error you get indicates that other vital information (in this case, which tokenizer to use) is missing as well. I strongly recommend to do a reimport from scratch.

Not much we can do, I'm afraid unless you have an idea what might have happened to the table content. So closing.
