### ISSUE TITLE
initialized module 'typing' (most likely due to a circular import)

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#3511]
I'm following https://nominatim.org/release-docs/develop/appendix/Install-on-Ubuntu-24/ but on Ubuntu 22, so Python version is 3.10 and osm2pgsql had to be compiled from source.

The gunicorn setup of `nominatim.service` uses `Environment="PYTHONPATH=/usr/local/lib/nominatim/lib-python/"` but such a path doesn't exist after https://github.com/osm-search/Nominatim/pull/3458

I replaced the line with `Environment="PYTHONPATH=$USERHOME/nominatim-venv/lib/python3.10/site-packages/nominatim_api"`

```
sudo rm /var/log/gunicorn-nominatim.log
sudo systemctl start nominatim.service
cat /var/log/gunicorn-nominatim.log

Error processing line 1 of /home/ubuntu/nominatim-venv/lib/python3.10/site-packages/_virtualenv.pth:

Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.10/site.py", line 192, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/home/ubuntu/nominatim-venv/lib/python3.10/site-packages/_virtualenv.py", line 40, in <module>
    from functools import partial
  File "/usr/lib/python3.10/functools.py", line 22, in <module>
    from types import GenericAlias
  File "/home/ubuntu/nominatim-venv/lib/python3.10/site-packages/nominatim_api/types.py", line 10, in <module>
    from typing import Optional, Union, Tuple, NamedTuple, TypeVar, Type, Dict, \
  File "/home/ubuntu/nominatim-venv/lib/python3.10/site-packages/nominatim_api/typing.py", line 12, in <module>
    from typing import Union, TYPE_CHECKING
ImportError: cannot import name 'Union' from partially initialized module 'typing' (most likely due to a circular import) (/home/ubuntu/nominatim-venv/lib/python3.10/site-packages/nominatim_api/typing.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site.py", line 636, in <module>
    main()
  File "/usr/lib/python3.10/site.py", line 619, in main
    known_paths = venv(known_paths)
  File "/usr/lib/python3.10/site.py", line 551, in venv
    addsitepackages(known_paths, [sys.prefix])
  File "/usr/lib/python3.10/site.py", line 406, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/python3.10/site.py", line 232, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.10/site.py", line 202, in addpackage
    import traceback
  File "/usr/lib/python3.10/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.10/linecache.py", line 8, in <module>
    import functools
  File "/usr/lib/python3.10/functools.py", line 22, in <module>
    from types import GenericAlias
  File "/home/ubuntu/nominatim-venv/lib/python3.10/site-packages/nominatim_api/types.py", line 10, in <module>
    from typing import Optional, Union, Tuple, NamedTuple, TypeVar, Type, Dict, \
  File "/home/ubuntu/nominatim-venv/lib/python3.10/site-packages/nominatim_api/typing.py", line 12, in <module>
    from typing import Union, TYPE_CHECKING
ImportError: cannot import name 'Union' from partially initialized module 'typing' (most likely due to a circular import) (/home/ubuntu/nominatim-venv/lib/python3.10/site-packages/nominatim_api/typing.py)
```

**Comment by lonvia** [comment]
The PYTHONPATH line should be removed completely. Running with the python from the venv takes care of paths.

Theoretically speaking: when setting PYTHONPATH manually it should be `Environment="PYTHONPATH=$USERHOME/nominatim-venv/lib/python3.10/site-packages` (without the `nominatim-api`, that is what causes the import confusion).
