### ISSUE TITLE
Exception during perpetual diff updates

### ISSUE THREAD

**Issue by james-astra** [osm-search/Nominatim#3528]
Hi sorry I have not followed the template, this is just an exception dump incase it is noteworthy. I hadn't noticed my diff had canned it after going strong for 2 or so months, now I'm 2 weeks behind because I forgot to enable restarted in my systemd service :D

Exception:
2024-08-19 16:31:45: Update completed. Import: 0:00:05. Indexing: 0:00:09 Total: 0:00:15. Remaining backlog: 0:01:26.
2024-08-19 16:31:46: Update completed. Import: 0:00:00. Total: 0:00:00. Remaining backlog: 0:01:27.
2024-08-19 16:31:46: No new changes. Sleeping for 60 sec.
2024-08-19 16:32:46  osm2pgsql version 1.9.2
2024-08-19 16:32:46  Database version: 16.3 (Ubuntu 16.3-1.pgdg22.04+1)
2024-08-19 16:32:46  PostGIS version: 3.4
2024-08-19 16:32:46  Loading properties from table '"public"."osm2pgsql_properties"'.
2024-08-19 16:32:46  Not using flat node file (same as on import).
2024-08-19 16:32:46  Using prefix 'planet_osm' (same as on import).
2024-08-19 16:32:46  Using style file '/usr/local/etc/nominatim/import-extratags.lua' (same as on import).
2024-08-19 16:32:47  Reading input files done in 1s.                                      
2024-08-19 16:32:47    Processed 1275 nodes in 0s - 1k/s
2024-08-19 16:32:47    Processed 337 ways in 1s - 337/s
2024-08-19 16:32:47    Processed 3 relations in 0s - 3/s
2024-08-19 16:32:48  Going over 15 pending ways
2024-08-19 16:32:48  Processing 15 pending ways took 0s at a rate of 0.00/s
2024-08-19 16:32:48  Going over 15 pending relations
2024-08-19 16:32:48  Processing 15 pending relations took 0s at a rate of 0.00/s
2024-08-19 16:32:48  Skipping stage 1c (no marked ways).
2024-08-19 16:32:48  No marked ways (Skipping stage 2).
2024-08-19 16:32:48  Done postprocessing on table 'planet_osm_nodes' in 0s
2024-08-19 16:32:48  Done postprocessing on table 'planet_osm_ways' in 0s
2024-08-19 16:32:48  Done postprocessing on table 'planet_osm_rels' in 0s
2024-08-19 16:32:48  All postprocessing on table 'place' done in 0s.
2024-08-19 16:32:48  osm2pgsql took 2s overall.
2024-08-19 16:32:48: Starting indexing rank (0 to 4) using 1 threads
2024-08-19 16:32:49: Starting rank 1 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 1

2024-08-19 16:32:49: Starting rank 2 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 2

2024-08-19 16:32:49: Starting rank 3 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 3

2024-08-19 16:32:49: Starting rank 4 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 4

2024-08-19 16:32:49: Starting indexing boundaries using 1 threads
2024-08-19 16:32:49: Starting boundaries rank 4 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 4

2024-08-19 16:32:49: Starting boundaries rank 5 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 5

2024-08-19 16:32:49: Starting boundaries rank 6 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 6

2024-08-19 16:32:49: Starting boundaries rank 7 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 7

2024-08-19 16:32:49: Starting boundaries rank 8 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 8

2024-08-19 16:32:49: Starting boundaries rank 9 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 9

2024-08-19 16:32:49: Starting boundaries rank 10 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 10

2024-08-19 16:32:49: Starting boundaries rank 11 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 11

2024-08-19 16:32:49: Starting boundaries rank 12 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 12

2024-08-19 16:32:49: Starting boundaries rank 13 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 13

2024-08-19 16:32:49: Starting boundaries rank 14 (using batch size 1)
2024-08-19 16:32:49: Done 1/1 in 0 @ 2.139 per second - FINISHED boundaries rank 14

2024-08-19 16:32:49: Starting boundaries rank 15 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 15

2024-08-19 16:32:49: Starting boundaries rank 16 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 16

2024-08-19 16:32:49: Starting boundaries rank 17 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 17

2024-08-19 16:32:49: Starting boundaries rank 18 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 18

2024-08-19 16:32:49: Starting boundaries rank 19 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 19

2024-08-19 16:32:49: Starting boundaries rank 20 (using batch size 1)
2024-08-19 16:32:49: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 20

2024-08-19 16:32:49: Starting boundaries rank 21 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 21

2024-08-19 16:32:50: Starting boundaries rank 22 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 22

2024-08-19 16:32:50: Starting boundaries rank 23 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 23

2024-08-19 16:32:50: Starting boundaries rank 24 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 24

2024-08-19 16:32:50: Starting boundaries rank 25 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED boundaries rank 25

2024-08-19 16:32:50: Starting indexing rank (5 to 25) using 1 threads
2024-08-19 16:32:50: Starting rank 5 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 5

2024-08-19 16:32:50: Starting rank 6 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 6

2024-08-19 16:32:50: Starting rank 7 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 7

2024-08-19 16:32:50: Starting rank 8 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 8

2024-08-19 16:32:50: Starting rank 9 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 9

2024-08-19 16:32:50: Starting rank 10 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 10

2024-08-19 16:32:50: Starting rank 11 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 11

2024-08-19 16:32:50: Starting rank 12 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 12

2024-08-19 16:32:50: Starting rank 13 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 13

2024-08-19 16:32:50: Starting rank 14 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 14

2024-08-19 16:32:50: Starting rank 15 (using batch size 1)
2024-08-19 16:32:50: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 15

2024-08-19 16:32:50: Starting rank 16 (using batch size 1)
2024-08-19 16:32:50: Done 7/7 in 0 @ 11.366 per second - FINISHED rank 16

2024-08-19 16:32:50: Starting rank 17 (using batch size 1)
2024-08-19 16:32:51: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 17

2024-08-19 16:32:51: Starting rank 18 (using batch size 1)
2024-08-19 16:32:51: Done 2/2 in 0 @ 8.656 per second - FINISHED rank 18

2024-08-19 16:32:51: Starting rank 19 (using batch size 1)
2024-08-19 16:32:51: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 19

2024-08-19 16:32:51: Starting rank 20 (using batch size 1)
2024-08-19 16:32:51: Done 21/21 in 0 @ 34.699 per second - FINISHED rank 20

2024-08-19 16:32:51: Starting rank 21 (using batch size 1)
2024-08-19 16:32:51: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 21

2024-08-19 16:32:51: Starting rank 22 (using batch size 1)
2024-08-19 16:32:52: Done 1/1 in 0 @ 6.542 per second - FINISHED rank 22

2024-08-19 16:32:52: Starting rank 23 (using batch size 1)
2024-08-19 16:32:52: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 23

2024-08-19 16:32:52: Starting rank 24 (using batch size 1)
2024-08-19 16:32:52: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 24

2024-08-19 16:32:52: Starting rank 25 (using batch size 1)
2024-08-19 16:32:52: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 25

2024-08-19 16:32:52: Starting indexing rank (26 to 30) using 1 threads
2024-08-19 16:32:52: Starting rank 26 (using batch size 1)
2024-08-19 16:32:53: Done 38/38 in 1 @ 28.710 per second - FINISHED rank 26

2024-08-19 16:32:53: Starting rank 27 (using batch size 1)
2024-08-19 16:32:53: Done 1/1 in 0 @ 6.642 per second - FINISHED rank 27

2024-08-19 16:32:53: Starting rank 28 (using batch size 1)
2024-08-19 16:32:53: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 28

2024-08-19 16:32:53: Starting rank 29 (using batch size 1)
2024-08-19 16:32:53: Done 0/0 in 0 @ 0.000 per second - FINISHED rank 29

2024-08-19 16:32:53: Starting rank 30 (using batch size 20)
2024-08-19 16:32:56: Done 124/124 in 3 @ 40.718 per second - FINISHED rank 30

2024-08-19 16:32:56: Starting rank 0 (using batch size 1)
2024-08-19 16:32:57: Done 12/12 in 0 @ 37.455 per second - FINISHED rank 0

2024-08-19 16:32:57: Starting interpolation lines (location_property_osmline) (using batch size 20)
Traceback (most recent call last):
  File "/usr/local/bin/nominatim", line 12, in <module>
    exit(cli.nominatim(module_dir='/usr/local/lib/nominatim/module',
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 225, in nominatim
    return get_set_parser().run(**kwargs)
  File "/usr/local/lib/nominatim/lib-python/nominatim/cli.py", line 121, in run
    return args.command.run(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 199, in run
    self._update(args)
  File "/usr/local/lib/nominatim/lib-python/nominatim/clicmd/replication.py", line 164, in _update
    indexer.index_full(analyse=False)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 140, in index_full
    if self.index_by_rank(26, 30) > 1000:
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 178, in index_by_rank
    total += self._index(runners.InterpolationRunner(analyzer), 20)
  File "/usr/local/lib/nominatim/lib-python/nominatim/indexer/indexer.py", line 222, in _index
    with WorkerPool(self.dsn, self.num_threads) as pool:
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 235, in __exit__
    self.finish_all()
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 185, in finish_all
    thread.wait()
  File "/usr/local/lib/nominatim/lib-python/nominatim/db/async_connection.py", line 128, in wait
    wait_select(self.conn)
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 758, in wait_select
    state = conn.poll()
psycopg2.errors.NumericValueOutOfRange: value "11111111111111111111" is out of range for type integer
CONTEXT:  PL/pgSQL function osmline_update() line 59 at FOR over SELECT rows

**Comment by mtmail** [comment]
Please search for existing issues first. See https://github.com/osm-search/Nominatim/issues/3527
